name = "telegram-d1-bot"
main = "index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB" # هذا الاسم يجب أن يطابق ما استخدمته في الكود (env.DB)
database_name = "rsd-x0"
database_id = "38bb02e0-1924-4c2b-8e63-d8385e05fc77"
